### ISSUE TITLE
Why isn't db-interceptor added in api_server.clj in the same way as inject-system?

### ISSUE THREAD

**Issue by jumarko** [jacekschae/learn-pedestal-course-files#15]
_I asked this same question via Chat but didn't get an answer so recording it here_.

My question: Why you are adding it on the route level again? 

I had no issues with adding it when starting the server like this: 
```
(cheffy-interceptors [(inject-system {:system/database database})
                            interceptors/db-interceptor])
```
I didn't get your point about having only the initial state of the database - isn't the interceptor invoked for every request anyway? 
I actually verified it is and also that the database contains the latest data by manually inserting a new recipe.

Here's how I'm currently adding the interceptor in `api-server/start-server`: https://github.com/jumarko/learn-pedestal/blob/main/src/main/cheffy/components/api_server.clj#L44

**Comment by jumarko** [comment]
Hi @jacekschae and thanks for the reply.
The argument of not having to acquire the db on every request makes sense.

I think what was and is confusing is your argument "we would get the db **at the initial state** of the conn".
What the _initial state_ even means here and why it matters? 
You load the dataset only when there's no data yet and if your DB is persistent on the disk (which it surely is for anything that's not a one-off experiment) then it's not a worry at all.

**Comment by jacekschae** [comment]
I'm wondering how I can explain this better. 

When you use Datomic and you do transactions you get something like this back:

```clojure
{:db-before #datomic.core.db.Db{:id "1a9a7ca8-6160-47e3-bcb0-99934fab54af",
                                :basisT 7,
                                :indexBasisT 0,
                                :index-root-id nil,
                                :asOfT nil,
                                :sinceT nil,
                                :raw nil},
 :db-after #datomic.core.db.Db{:id "1a9a7ca8-6160-47e3-bcb0-99934fab54af",
                               :basisT 8,
                               :indexBasisT 0,
                               :index-root-id nil,
                               :asOfT nil,
                               :sinceT nil,
                               :raw nil},
 :tx-data [#datom[13194139533320 50 #inst"2022-06-13T07:34:16.888-00:00" 13194139533320 true]
           #datom[101155069755519 79 #uuid"691bafdb-d588-4328-a010-0ff973d02f71" 13194139533320 true]
           #datom[101155069755519 81 "name" 13194139533320 true]
           #datom[101155069755519 85 true 13194139533320 true]
           #datom[101155069755519 82 30 13194139533320 true]
           #datom[101155069755519 84 "img" 13194139533320 true]
           #datom[101155069755519 80 101155069755496 13194139533320 true]],
 :tempids {}}
```

There is one property there that shows the time basis: `:basisT` in the `db-before` it's `7` and in the `db-after` it's `8`. This is what I refer to initial state (`:basisT 7`) -- after the initial set of transactions -- including the schema data and seed. 

Try to add `db` on the system start just as in the first comment and then do some transactions and query the `db` added on the system start -- none of them will be there, because after adding some transactions the `:basisT` might be 11 or 12, yet the db created at the system start is :basisT of 7 and whatever you added with the transactions it won't be available at since you are querying `:basisT7` and you should be querying the latests `:basisT` which is obtain when a request arrives to the system with the `interceptors/db-interceptor`. 

I hope this is clearer a bit and I hope I'm answering the question you are wondering about.

**Comment by jumarko** [comment]
The example definitely helps when talking about this thing :).

However, I don't your conclusion is correct.
As I said before: 
> isn't the interceptor invoked for every request anyway?
I actually verified it is and also that the database contains the latest data by manually inserting a new recipe.

So I believe I get a fresh database for every request because the interceptor is invoked for every request.
It's only the interceptor that's added at the start of the system but the database is "created" from the connection every time a new request is made: https://github.com/jumarko/learn-pedestal/blob/develop/src/main/cheffy/interceptors.clj#L9
```
(defn- inject-db [ctx]
  ;; grab the connection injected by the system interceptor (see `cheffy.components.api-server/cheffy-interceptors`),
  ;; create the db and add it to the context
  (let [conn (get-in ctx [:request :system/database :conn])
        db (d/db conn)]
    (println "Adding current db value to the request context")
    (assoc-in ctx [:request :system/database :db] db)))
```

**Comment by jacekschae** [comment]
Yes if you use the `db-interceptor`, it is since it goes over the request -- still not a correct thing to do for every request. I would say the the `db` value is obtained on every request. The `db` is created only once on the start of the system. On the other hand if you obtain `db` value on system start you would get only the initial state of the `db` -- `:basisT 7`. Hope this helps.

**Comment by jumarko** [comment]
I think it's now more-or-less clear :).
The approach I took works fine but might not be ideal if most of the routes do not require connection to the database.
